name: geosalud
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor_flutter: ^1.7.0   # orm sqlite
  equatable: ^0.5.1
  bloc: ^0.15.0           #state manager core
  flutter_bloc: ^0.21.0   #state manager
  #provider: ^3.0.0+1     #state manager
 
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^1.7.0   # orm sqlite
  build_runner:

flutter:
  uses-material-design: true

  assets:
   - assets/images/login.jpg
   - assets/images/logomd.png
   - assets/images/logosm.png
   - assets/images/avatar.png